### ISSUE TITLE
Topics in the OData Introduction ( http://odata.github.io/WebApi/ ) are not in order.

### ISSUE THREAD

**Issue by kiewic** [OData/odata.github.io#17]
Hello,

While reading http://odata.github.io/WebApi/ , I got surprised to see **How To Debug** just after reading **Write a simple OData V4 service**. Then i realized the topics 10 and 11 are sorted between 1 and 2.

It would be nice to fix the order of the topics.

**Comment by xuzhg** [comment]
@kiewic It's fixed. Can you try it again. Thanks your feedback.

**Comment by kiewic** [comment]
Awesome! Thank you.
