### ISSUE TITLE
How to contribute to site content

### ISSUE THREAD

**Issue by moander** [OData/odata.github.io#18]
I found a few bugs in  the [RESTier tutorial](http://odata.github.io/RESTier/) but I cant figure out where on github the content is located ;)

**Comment by chinadragon0515** [comment]
It is located in https://github.com/OData/RESTier/ gh-pages branch.
You can open issue on https://github.com/OData/RESTier/, and send us pull request, we will review and merge pull request.

thanks in advance for your contributions.
I close this issue now. Let us know if you have more questions.
