### ISSUE TITLE
Images don't show up in http://odata.github.io

### ISSUE THREAD

**Issue by congysu** [OData/odata.github.io#5]
For example: http://odata.github.io/WebApi/#02-01-model-builder-abstract

**Comment by dingeins** [comment]
I know the fix. Just put all the images in a folder like `/assets/` and reference them in post by `href="{{site.baseurl}}/assets/xxx.png"`, in which {{site.baseurl}} refers to subsite segments such as `/WebApi` or `/odata.net`.

Let me help on this.

**Comment by dingeins** [comment]
Fixed and updated. Please have a look.

**Comment by congysu** [comment]
Thanks.  It works.
